version: '2'
services:
  filebeat:
    image: eason02/filebeat-alpine:5.6.3
    container_name: filebeat-alpine-5.6.3
    restart: always
    labels:
      io.rancher.container.pull_image: always
    environment:
      - env=QA
      - logstash=localhost
      - project=demoproject
    network_mode: host
    volumes:
      - /var/lib/filebeat/:/etc/filebeat/data
      - /home/user/logs:/home/user/
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
